nyanpalette:	.defpal $013,$777,$000,$000,$000,$000,$000,$000,$000,$000,$000,$000,$000,$000,$000,$000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_0:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_1:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_2:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_3:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11111100,\
$11111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_4:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_5:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111111,\
$00111111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_6:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_7:	.defchr $4000, $0,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_8:	.defchr $4000, $0,\
$11111100,\
$11111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_9:	.defchr $4000, $0,\
$00111111,\
$00111111,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_10:	.defchr $4000, $0,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_11:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_12:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000011,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_13:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_14:	.defchr $4000, $0,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$11111100,\
$11111100,\
$11111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_15:	.defchr $4000, $0,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$00111111,\
$00111111,\
$00111111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_16:	.defchr $4000, $0,\
$00000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_17:	.defchr $4000, $0,\
$11111100,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_18:	.defchr $4000, $0,\
$00111111,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_19:	.defchr $4000, $0,\
$11000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_20:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$01111000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_21:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000111,\
$00000111,\
$00000111,\
$00000111,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_22:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$10000111,\
$10000111,\
$10000111,\
$10000111,\
$01111000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_23:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$10000000,\
$10000000,\
$10000000,\
$10000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_24:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_25:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_26:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000111,\
$00000111,\
$00000111,\
$00000111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_27:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$10000000,\
$10000000,\
$10000000,\
$10000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_28:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg01_29:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$01111000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000



nyan_bg01_bat:	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 1)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 2)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 3)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 5)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 6)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 7)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 9)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 10)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 11)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 12)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 13)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 12)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 14)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 15)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 13)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 16)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 17)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 18)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 19)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 16)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 19)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 20)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 21)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 22)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 23)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 24)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 25)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 26)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 27)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 28)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 28)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 29)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 29)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 26)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 27)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + TILE_SIZE * 0)

