; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_0:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_1:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_2:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_3:	.defchr $4000, $0,\
$00000000,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_4:	.defchr $4000, $0,\
$00000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_5:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_6:	.defchr $4000, $0,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_7:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$01111000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_8:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_9:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_10:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000111,\
$00000111,\
$00000111,\
$00000111,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_11:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$10000000,\
$10000000,\
$10000000,\
$10000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_12:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_13:	.defchr $4000, $0,\
$00000000,\
$11111100,\
$11111100,\
$11111100,\
$11111100,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_14:	.defchr $4000, $0,\
$00000000,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_15:	.defchr $4000, $0,\
$00000000,\
$00111111,\
$00111111,\
$00111111,\
$00111111,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_16:	.defchr $4000, $0,\
$00000000,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_17:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00001111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_18:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_19:	.defchr $4000, $0,\
$00001111,\
$00001111,\
$00001111,\
$11110000,\
$11110000,\
$11110000,\
$11110000,\
$00001111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_20:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$11111111,\
$11111111,\
$11111111,\
$11111111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_21:	.defchr $4000, $0,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00001111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_22:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000111,\
$00000111,\
$00000111,\
$00000111,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_23:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$10000000,\
$10000000,\
$10000000,\
$10000000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_24:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$01111000,\
$00000111,\
$00000111,\
$00000111,\
$00000111,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg05_25:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$01111000,\
$10000000,\
$10000000,\
$10000000,\
$10000000,\
$00000000

NYAN_BG05_OFFSET .equ NYAN_BG04_OFFSET + NYAN_BG04_LENGTH

nyan_bg05_bat:	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 1)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 2)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 3)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 5)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 5)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 6)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 6)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 3)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 7)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 9)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 10)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 11)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 10)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 11)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 7)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 9)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 5)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 12)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 3)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 13)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 14)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 15)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 16)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 6)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 17)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 18)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 19)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 20)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 21)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 22)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 23)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 24)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 25)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG05_OFFSET + TILE_SIZE * 0)

