; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_0:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_1:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_2:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00111100,\
$00111100,\
$00111100,\
$00111100,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_3:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_4:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_5:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_6:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_7:	.defchr $4000, $0,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_8:	.defchr $4000, $0,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_9:	.defchr $4000, $0,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_10:	.defchr $4000, $0,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_11:	.defchr $4000, $0,\
$00111100,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_12:	.defchr $4000, $0,\
$00000000,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_13:	.defchr $4000, $0,\
$00000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_14:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111111,\
$00111111,\
$00111111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_15:	.defchr $4000, $0,\
$00000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000011,\
$11000011,\
$11000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_16:	.defchr $4000, $0,\
$11000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000011,\
$11000011,\
$11000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_17:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11111100,\
$11111100,\
$11111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_18:	.defchr $4000, $0,\
$00111111,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_19:	.defchr $4000, $0,\
$11000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000011,\
$00000011,\
$00000011

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_20:	.defchr $4000, $0,\
$11000011,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$11000000,\
$11000000,\
$11000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_21:	.defchr $4000, $0,\
$11111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_22:	.defchr $4000, $0,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_23:	.defchr $4000, $0,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_24:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_25:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$01111111,\
$01111111,\
$01111111,\
$01111111,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_26:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$10000111,\
$10000111,\
$10000111,\
$10000111,\
$01111000,\
$01111000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_27:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$11111000,\
$11111000,\
$11111000,\
$11111000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_28:	.defchr $4000, $0,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$01111000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_29:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00111100,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_30:	.defchr $4000, $0,\
$00000000,\
$00000011,\
$00000011,\
$00000011,\
$00000011,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_31:	.defchr $4000, $0,\
$00111100,\
$11000011,\
$11000011,\
$11000011,\
$11000011,\
$00111100,\
$00111100,\
$00111100

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_32:	.defchr $4000, $0,\
$00000000,\
$11000000,\
$11000000,\
$11000000,\
$11000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_33:	.defchr $4000, $0,\
$00111100,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_34:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000111

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_35:	.defchr $4000, $0,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$10000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_36:	.defchr $4000, $0,\
$00000111,\
$00000111,\
$00000111,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

; TODO: change the vram address (1st number) and palette number (2nd number)
nyan_bg07_37:	.defchr $4000, $0,\
$10000000,\
$10000000,\
$10000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000,\
$00000000

NYAN_BG07_OFFSET .equ NYAN_BG06_OFFSET + NYAN_BG06_LENGTH

nyan_bg07_bat:	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 1)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 2)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 1)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 3)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 4)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 5)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 6)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 7)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 8)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 9)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 10)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 11)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 2)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 11)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 12)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 13)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 14)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 15)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 16)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 17)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 18)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 19)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 20)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 21)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 22)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 23)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 24)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 25)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 26)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 27)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 28)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 29)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 30)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 31)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 32)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 33)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 34)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 35)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 36)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 37)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)
	.dw BATVAL(0, TILE_START + NYAN_BG07_OFFSET + TILE_SIZE * 0)

